### ISSUE TITLE
Put a screenshot in readme

### ISSUE THREAD

**Issue by mcscope** [brangerbriz/wifi-data-safari#21]
Hey a screenshot in the readme would be great to show off the cool visualization

**Comment by nbriz** [comment]
yep ^__^ been meaning to update the README ( split them up in to separate READMEs >> one for the workshop, another for the installation, etc. )

**Comment by brannondorsey** [comment]
Thanks for the note! I've added a screenshot of the 3D habitat view. This should work for now, until we get a chance to update the README in the way that @nbriz mentioned.
