### ISSUE TITLE
admin should also be an AP

### ISSUE THREAD

**Issue by nbriz** [brangerbriz/wifi-data-safari#7]
everyone on the data safari needs to be on the same network ( obviously ) should that network be broadcast from the admin computer? ( hostapd? ) if so will we need 2 network devices ( one for mon0 && one to act as the AP ), which is then maybe tethering it's connection to the Internet from a phone ( if we need it, for maps for example )... which might require a 3rd network interface?

**Comment by brannondorsey** [comment]
This is now working using [mitm-router](https://github.com/brannondorsey/mitm-router). Also working via the WiFi pineapple.
